### ISSUE TITLE
Disable EntityCache

### ISSUE THREAD

**Issue by alexandr-san4ez** [analogueorm/analogue#120]
Hello, you have a great product!
Can I disable caching for the entity? Or clear the cache when I need?

**Comment by RemiCollin** [comment]
The cache is used internally to track the changes made to an Entity, so it cannot be disabled nor should it be cleared. It basically holds the original attributes from a Query and compare them on an update operation. I think there's room for optimization there though, as entity object that has been cleared from memory would still exists in the cache. I'll think about this. 

So it's not a Level 2 cache, that would retrieve an entity's attributes from the cache instead of making a new Query. Such a cache isn't implemented yet.

Hope it answers your question

**Comment by alexandr-san4ez** [comment]
I fill a database of entities that I do not use in the future. Because of the large number of items in the cache memory overflow occurs. Can you recommend something?
Thanks.

**Comment by RemiCollin** [comment]
The problem in this situation is that there is no way to track object by reference in PHP, as a deleted object's reference can be reused by another object.. So I guess the solution here would indeed be to manually clear the cache. 

I added a clear() method to the entity cache. You can use it this way :

```
    $mapper->getEntityCache()->clear()
```

I think it should fix your issue.

**Comment by alexandr-san4ez** [comment]
Thanks for the help.
